import { useState, useEffect } from 'react'
import api from '../../api/axios'
import toast from 'react-hot-toast'
import { Spinner, PageHeader, EmptyState } from '../../components/UI'

export default function CompanyReports() {
  const [reports, setReports] = useState([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    api.get('/tasks/reports/')
      .then(({ data }) => setReports(data.results || data))
      .catch(() => toast.error('Failed to load reports.'))
      .finally(() => setLoading(false))
  }, [])

  return (
    <div className="space-y-6">
      <PageHeader title="Reports" subtitle="Reports generated for your projects" />

      {loading ? <Spinner /> : reports.length === 0 ? (
        <EmptyState message="No reports available yet. Reports are generated by the admin team." />
      ) : (
        <div className="space-y-4">
          {reports.map(r => (
            <div key={r.id} className="card">
              <div className="flex items-start justify-between gap-4 mb-3">
                <div>
                  <h3 className="font-semibold text-slate-800">{r.task_title}</h3>
                  <p className="text-xs text-slate-400 mt-0.5">
                    Generated {new Date(r.generated_at).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}
                  </p>
                </div>
                <span className="text-xs bg-blue-50 text-blue-600 px-2.5 py-1 rounded-full font-medium">Report</span>
              </div>
              <p className="text-sm text-slate-600 leading-relaxed">{r.report_content}</p>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
